### ISSUE TITLE
Infinite loop?

### ISSUE THREAD

**Issue by TorkelV** [c-b-h/data-binding#1]
https://github.com/shortcut/data-binding/blob/dc720b6a61ab23ffe30080ce3b30901e12054d52/library/src/main/java/se/ingenuity/databinding/extension/ViewExt.kt#L9

```
while ((parent as? View)?.id != id) {
    parent = parent.parent
}
```
Wouldn't this either crash or cause an infinite loop if the parent doesn't exist?

**Comment by c-b-h** [comment]
If the id that is passed is not in the tree hierarchy, you are right, this might result in an infinite loop.

Maybe you can fix it. Just remember that `ViewParent` is either another `View` or `Window` and finally `null` when reaching the top of the tree hierarchy. @TorkelV

**Comment by TorkelV** [comment]
https://github.com/shortcut/data-binding/pull/2/files
